apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: 6vjdlm.5fjf1wu3sk1m0kp2 # Get your Token with "kubeadm token generate"
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.0.1.2  # Private IP from your Host
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock # Add this here
  imagePullPolicy: IfNotPresent
  name: mykubu-1 # Use the right hostname
  taints: null
  kubeletExtraArgs:
    node-ip: 10.0.1.2 # Private IP from your host
    cloud-provider: external # External Provider for the hccm later
---
apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
    - dogruel.me
    - 10.0.1.2
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: 1.30.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16 # Use this Subnet for your Pods
scheduler: {}