apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.0.1.2:6443 # Private IP from your Controlplane Node. mykubu-1
    token: 6vjdlm.5fjf1wu3sk1m0kp2 # Same Token as you generated for InitConfiguration.yaml
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: 6vjdlm.5fjf1wu3sk1m0kp2 # Same Token as you generated for InitConfiguration.yaml
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock # Add this here
  imagePullPolicy: IfNotPresent
  name: mykubu-2
  taints: null
  kubeletExtraArgs:
    cloud-provider: external # External Provider for the hccm later
    node-ip: 10.0.1.3 # Private IP from your Host